name: Experiment
on:
  push:

jobs:
  run_validation_experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install MLOps Dependencies
        run: |
          pip install pip install --index-url https://pypi.org/simple/ --extra-index-url https://test.pypi.org/simple/ Akevilli-DS-Internship==1.0.3
          pip install pandas dvc[gdrive] neptune-client xgboost

      - name: Experiment
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_JSON }}
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
          NEPTUNE_PROJECT: ${{ secrets.NEPTUNE_PROJECT }}
        run: |
          echo "$GDRIVE_CREDENTIALS_DATA" > gdrive_key.json
          dvc remote modify gdrive gdrive_service_account_json_file_path gdrive_key.json
          dvc pull
          python experiment.py