name: Experiment
on:
  push:

jobs:
  run_validation_experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install MLOps Dependencies
        run: |
          pip install pip install --index-url https://pypi.org/simple/ --extra-index-url https://test.pypi.org/simple/ Akevilli-DS-Internship==1.0.3
          pip install pandas dvc[gdrive] neptune-client xgboost

      - name: Prepare Secure DVC Environment
        env:
          GDRIVE_SERVICE_ACCOUNT_KEY_B64: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
          NEPTUNE_PROJECT: ${{ secrets.NEPTUNE_PROJECT }}
        run: |
          echo "$GDRIVE_SERVICE_ACCOUNT_KEY_B64" | base64 -d > gdrive_key.json
          export DVC_CONFIG_REMOTE_GDRIVE_GDRIVE_SERVICE_ACCOUNT_JSON_FILE_PATH=gdrive_key.json
          dvc pull
          python experiment.py