name: Experiment
on:
  push:
    branches: [ "master" ]

jobs:
  run_experiment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      AIRFLOW_IMAGE_NAME: ${{ secrets.AIRFLOW_IMAGE_NAME }}
      NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
      NEPTUNE_PROJECT: ${{ secrets.NEPTUNE_PROJECT }}
      GDRIVE_SERVICE_ACCOUNT_KEY: ${{ secrets.GDRIVE_SERVICE_ACCOUNT_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create empty .env file
        run: touch .env

      - name: Service account json file creating
        working-directory: ./.dvc
        run: echo "$GDRIVE_SERVICE_ACCOUNT_KEY" > service_account.json

      - name: Build docker-compose
        run: docker compose build

      - name: Push docker images
        run: docker compose push