name: Experiment
on:
  push:

jobs:
  run_validation_experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install MLOps Dependencies
        run: |
          pip install -i https://test.pypi.org/simple/ Akevilli-DS-Internship==1.0.3
          pip install pandas dvc[gdrive] neptune-client xgboost

      - name: Execute Experiment and Track Results
        env:
          NEPTUNE_API_TOKEN: ${{ secrets.NEPTUNE_API_TOKEN }}
          NEPTUNE_PROJECT: ${{ secrets.NEPTUNE_PROJECT }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          DVC_CONFIG_REMOTE_GDRIVE_GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          DVC_CONFIG_REMOTE_GDRIVE_GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
        run: |
          dvc pull
          python experiment.py